START TRANSACTION;

-- CREATE ID's =====================================================
SET @CASH_TXN_ID = UUID();
SET @GL_HEADER_ID = UUID();

SET @DEBIT_GL_CODE = -5000;
SET @CREDIT_GL_CODE = 1000;

SET @TXN_AMOUNT = 39.98;
SET @TXN_DESC = 'Choc Milk';
SET @SOURCE_TYPE = 'CASH';
SET @TXN_DATE = '2026-02-02';

# SET @ACCOUNT_ID = '4c005aee-6041-4659-a7ed-0314a8876865'; -- DEV_ACCOUNT
SET @ACCOUNT_ID = 'c5201fe4-02a2-11f1-8f82-0242ac160002'; -- DEV_ACCOUNT_001

-- INSERT CASH_TXN =====================================================
INSERT INTO CASH_TXN
    (CASH_TXN_ID, TRANSACTION_SOURCE, DATE, DETAILS, AMOUNT, ACCOUNT_ID)
VALUES
    (@CASH_TXN_ID, @SOURCE_TYPE, @TXN_DATE, @TXN_DESC, @TXN_AMOUNT,  @ACCOUNT_ID);

-- INSERT GL_HEADER =====================================================
INSERT INTO GL_HEADER
    (GL_HEADER_ID, SOURCE_TYPE, TRANSACTION_ID, details, ACCOUNT_ID)
VALUES
    (@GL_HEADER_ID, @SOURCE_TYPE, @CASH_TXN_ID, @TXN_DESC, @ACCOUNT_ID);

-- INSERT GL_LINES =====================================================
INSERT INTO GL_LINE
    (GL_LINE_ID, GL_ACCOUNT_ID, GL_HEADER_ID, DEBIT_CREDIT, AMOUNT, ACCOUNT_ID)
VALUES
    (UUID(), (SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT_CODE = @DEBIT_GL_CODE AND ACCOUNT_ID=@ACCOUNT_ID), @GL_HEADER_ID, 'DEBIT',  @TXN_AMOUNT, @ACCOUNT_ID),
    (UUID(), (SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT_CODE = @CREDIT_GL_CODE AND ACCOUNT_ID=@ACCOUNT_ID), @GL_HEADER_ID, 'CREDIT', @TXN_AMOUNT, @ACCOUNT_ID);

COMMIT;