SET @ACCOUNT_ID='7e7e02f7-035a-11f1-8f82-0242ac160002';
SELECT
    *
FROM
    CASH_TXN

LEFT JOIN GL_HEADER ON CASH_TXN.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE CASH_TXN.ACCOUNT_ID=@ACCOUNT_ID

