# SET @accountID = 'cd2fe940-0398-11f1-8f82-0242ac160002'; # MAIN
SET @ACCOUNT_ID='7e7e02f7-035a-11f1-8f82-0242ac160002'; # DEV


SELECT
    CASH_TXN.CASH_TXN_ID,
    CASH_TXN.ACCOUNT_id,
    CASH_TXN.DATE,
    CASH_TXN.DETAILS,
    CASH_TXN.AMOUNT,
    CASH_TXN.CREATED,
    CASH_TXN.MERCHANT_ID,

    CASH_TXN.RECEIVABLE,
    CASH_TXN.DEBTOR_ID,

    CASH_TXN.DAY,
    CASH_TXN.DAY_OF_WEEK,
    CASH_TXN.WEEK,
    CASH_TXN.MONTH,
    CASH_TXN.MONTH_NAME,
    CASH_TXN.YEAR,

    MERCHANT.NAME AS 'MERCHANT_NAME',

    GL_HEADER.SOURCE_TYPE AS 'SOURCE',

    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_CODE

FROM
    CASH_TXN

LEFT JOIN GL_HEADER ON CASH_TXN.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN MERCHANT ON CASH_TXN.MERCHANT_ID = MERCHANT.MERCHANT_ID

WHERE
    GL_HEADER.SOURCE_TYPE = 'CASH'
    AND GL_ACCOUNT.GL_ACCOUNT_TYPE <> 'ASSET'
    AND CASH_TXN.ACCOUNT_ID = @ACCOUNT_ID

UNION ALL

SELECT
    CC.CREDIT_CARD_TXN_ID,
    CC.ACCOUNT_id,
    CC.DATE,
    CC.DETAILS,
    CC.AMOUNT,
    CC.CREATED,
    CC.MERCHANT_ID,

    CC.RECEIVABLE,
    CC.DEBTOR_ID,

    CC.DAY,
    CC.DAY_OF_WEEK,
    CC.WEEK,
    CC.MONTH,
    CC.MONTH_NAME,
    CC.YEAR,

    MERCHANT.NAME AS 'MERCHANT_NAME',

    GL_HEADER.SOURCE_TYPE AS 'SOURCE',

    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_CODE

FROM
    CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN MERCHANT ON CC.MERCHANT_ID = MERCHANT.MERCHANT_ID

WHERE
    GL_HEADER.SOURCE_TYPE = 'CREDIT_CARD' AND
    CC.ACCOUNT_ID=@ACCOUNT_ID AND
    GL_ACCOUNT_TYPE = 'ASSET' AND GL_LINE.DEBIT_CREDIT = 'CREDIT' AND (GL_ACCOUNT_CODE =1000 OR GL_ACCOUNT_CODE BETWEEN 5000 AND 5999)

ORDER BY
    DATE DESC
;