SET @ACCOUNT_ID='7e7e02f7-035a-11f1-8f82-0242ac160002';
SET @TXN_ID='45ca61b7-e70f-4ad3-ae5f-86089274ed51';

SELECT
    CASH_TXN.AMOUNT,
    GL_LINE.AMOUNT,
    GL_ACCOUNT_CODE,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_LINE.DEBIT_CREDIT,
    GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_ID
FROM
    CASH_TXN

LEFT JOIN GL_HEADER ON CASH_TXN.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    CASH_TXN.ACCOUNT_ID=@ACCOUNT_ID
    AND CASH_TXN.CASH_TXN_ID=@TXN_ID