START TRANSACTION;

SET @TXN_GL_HEADER_ID='04ff8b61-0fff-45de-a8fb-d44a856616cd';
SET @TXN_ACCOUNT_ID='7e7e02f7-035a-11f1-8f82-0242ac160002';
SET @TXN_GL_ACCOUNT_CODE='5001';
/*
# FIND THE LINE WHICH THE DIAMOND_USER'S BANK ACCOUNT
SELECT
    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_HEADER.GL_HEADER_ID
FROM GL_ACCOUNT

LEFT JOIN GL_LINE ON GL_ACCOUNT.GL_ACCOUNT_ID = GL_LINE.GL_ACCOUNT_ID
LEFT JOIN GL_HEADER ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID
WHERE
    GL_HEADER.GL_HEADER_ID=@TXN_GL_HEADER_ID AND
    GL_ACCOUNT.GL_ACCOUNT_TYPE IN ('ASSET') AND
    GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID;
*/

# FIND THE LINE WHICH IS AN INCOME OR EXPENSE
#SELECT GL_ACCOUNT.GL_ACCOUNT_ID, GL_ACCOUNT_NAME FROM GL_LINE LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID WHERE GL_HEADER_ID=@TXN_GL_HEADER_ID AND  GL_ACCOUNT_TYPE IN ('INCOME', 'EXPENSE') AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID;



 # UPDATING THE EXPENSE ACCOUNT
UPDATE
    GL_LINE

SET
    DEBIT_CREDIT='DEBIT',

    GL_ACCOUNT_ID=(SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT.GL_ACCOUNT_CODE=@TXN_GL_ACCOUNT_CODE AND GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID)

WHERE
    GL_LINE.GL_HEADER_ID=@TXN_GL_HEADER_ID
    #   WORKING
    AND GL_ACCOUNT_ID=(SELECT GL_ACCOUNT.GL_ACCOUNT_ID FROM GL_LINE LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID WHERE GL_HEADER_ID=@TXN_GL_HEADER_ID AND  GL_ACCOUNT_TYPE IN ('INCOME', 'EXPENSE') AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID) # FIND THE LINE WHICH IS AN INCOME OR EXPENSE
    AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID;

# UPDATING THE BANK ACCOUNT
UPDATE
    GL_LINE

SET
    DEBIT_CREDIT='CREDIT',
    GL_ACCOUNT_ID=(SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT.GL_ACCOUNT_CODE=1000 AND GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID) # SETTING THE DIAMOND_USER'S BANK ACCOUNT

WHERE
    GL_LINE.GL_HEADER_ID=@TXN_GL_HEADER_ID
#     AND GL_ACCOUNT_ID=(SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT_TYPE IN ('ASSET') AND GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID) # TARGETING THE LINE WHICH DEALS WITH THE BANK ACCOUNT

    AND GL_ACCOUNT_ID=(SELECT
    GL_ACCOUNT.GL_ACCOUNT_ID
FROM GL_ACCOUNT

LEFT JOIN GL_LINE ON GL_ACCOUNT.GL_ACCOUNT_ID = GL_LINE.GL_ACCOUNT_ID
LEFT JOIN GL_HEADER ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID
WHERE
    GL_HEADER.GL_HEADER_ID=@TXN_GL_HEADER_ID AND
    GL_ACCOUNT.GL_ACCOUNT_TYPE IN ('ASSET') AND
    GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID)

    AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID;

COMMIT;

/*

SET @TXN_GL_HEADER_ID='04ff8b61-0fff-45de-a8fb-d44a856616cd';
SET @TXN_ACCOUNT_ID='7e7e02f7-035a-11f1-8f82-0242ac160002';

SELECT
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    GL_LINE.DEBIT_CREDIT
FROM
    GL_LINE

LEFT JOIN GL_HEADER ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_LINE_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID
    AND GL_LINE.GL_HEADER_ID=@TXN_GL_HEADER_ID


