START TRANSACTION;

SET @NEW_ACCOUNT_ID= UUID();
SET @NEW_DIAMOND_USER_ID=UUID();
SET @NEW_EMAIL='grahamben7@gmail.com';
SET @NEW_FIRST_NAME='Ben';
SET @NEW_LAST_NAME='Graham';
SET @NEW_DATE_OF_BIRTH='2001-05-08';

INSERT INTO
    DIAMOND_USER (ACCOUNT_ID, DIAMOND_USER_ID, EMAIL, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH)
VALUES
     (@NEW_ACCOUNT_ID, @NEW_DIAMOND_USER_ID, @NEW_EMAIL, @NEW_FIRST_NAME, @NEW_LAST_NAME, @NEW_DATE_OF_BIRTH);


INSERT INTO
    GL_ACCOUNT (GL_ACCOUNT_ID, GL_ACCOUNT_TYPE, GL_ACCOUNT_CODE, GL_ACCOUNT_NAME, ACCOUNT_ID)

VALUES
    (UUID(), 'ASSET', -1000, 'Sundry Asset', @NEW_ACCOUNT_ID),
    (UUID(), 'ASSET', 1000, 'Bank', @NEW_ACCOUNT_ID),

    (UUID(), 'LIABILITY', -2000, 'Sundry Liability', @NEW_ACCOUNT_ID),
    (UUID(), 'LIABILITY', 2000, 'Credit Card', @NEW_ACCOUNT_ID),

    (UUID(), 'EQUITY', -3000, 'Sundry Owner Equity', @NEW_ACCOUNT_ID),
    (UUID(), 'EQUITY', 3000, 'Owner Equity', @NEW_ACCOUNT_ID),

   (UUID(), 'INCOME', -4000, 'Sundry Income', @NEW_ACCOUNT_ID),
   (UUID(), 'INCOME', 4000, 'Base Income', @NEW_ACCOUNT_ID),

   (UUID(), 'EXPENSE', -5000, 'Sundry Expense', @NEW_ACCOUNT_ID),
   (UUID(), 'EXPENSE', -5001, 'Credit Card Repayment', @NEW_ACCOUNT_ID),
   (UUID(), 'EXPENSE', 5000, 'Base Expense', @NEW_ACCOUNT_ID);

COMMIT;