START TRANSACTION;

SET @ACCOUNT_ID='9d57a4b3-14c1-11f1-a3e0-ce6cdc3544e3';

DELETE FROM CASH_TXN WHERE ACCOUNT_ID=@ACCOUNT_ID;
DELETE FROM CREDIT_CARD_TXN WHERE ACCOUNT_ID=@ACCOUNT_ID;

DELETE FROM GL_HEADER WHERE ACCOUNT_ID=@ACCOUNT_ID;
DELETE FROM GL_LINE WHERE ACCOUNT_ID=@ACCOUNT_ID;
DELETE FROM GL_ACCOUNT WHERE ACCOUNT_ID=@ACCOUNT_ID;


DELETE FROM DIAMOND_USER WHERE ACCOUNT_ID=@ACCOUNT_ID;

DELETE FROM DEBTOR WHERE ACCOUNT_ID=@ACCOUNT_ID;
DELETE FROM RECEIVABLE_TXN WHERE ACCOUNT_ID=@ACCOUNT_ID;

SELECT * FROM DIAMOND_USER;

COMMIT;