START TRANSACTION;
INSERT INTO DIAMOND_TRANSACTION
    (
        DIAMOND_TRANSACTION_ID,
        ACCOUNT_ID,
        AMOUNT,
        DETAILS,
        SOURCE,
        GL_ACCOUNT_ID,
        MERCHANT_ID,
        RECEIVABLE,
        DEBTOR_ID,
        DATE,
        DAY,
        DAY_OF_YEAR,
        DAY_OF_WEEK,
        WEEK,
        MONTH,
        YEAR,
        CREATED
    )

SELECT
    C.CASH_TXN_ID,          -- TRANSACTION_ID
    C.ACCOUNT_ID,            -- ACCOUNT_ID
    C.AMOUNT,                -- AMOUNT
    C.DETAILS,               -- DETAILS
    C.TRANSACTION_SOURCE,    -- SOURCE
    GL_ACCOUNT.GL_ACCOUNT_ID, -- GL_ACCOUNT_ID
    C.MERCHANT_ID,           -- MERCHANT_ID
    C.RECEIVABLE,            -- RECEIVABLE
    C.DEBTOR_ID,             -- DEBTOR_ID
    C.DATE,                  -- DATE
    C.DAY,                   -- DAY
    NULL,                    -- DAY_OF_YEAR
    C.DAY_OF_WEEK,           -- DAY_OF_WEEK
    C.WEEK,                  -- WEEK
    C.MONTH,                 -- MONTH
    C.YEAR,                  -- YEAR
    C.CREATED                -- CREATED

FROM CASH_TXN C

INNER JOIN GL_HEADER ON C.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
INNER JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
INNER JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
INNER JOIN MERCHANT ON C.MERCHANT_ID = MERCHANT.MERCHANT_ID

WHERE GL_ACCOUNT_TYPE <> 'ASSET';

SELECT
    D.DATE,
    D.DETAILS,
    D.AMOUNT,
    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    D.MERCHANT_ID,
    MERCHANT.NAME

FROM
    DIAMOND_TRANSACTION D

LEFT JOIN GL_HEADER ON D.DIAMOND_TRANSACTION_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN MERCHANT ON D.MERCHANT_ID = MERCHANT.MERCHANT_ID;

COMMIT;

DELETE FROM
    DIAMOND_TRANSACTION
WHERE GL_ACCOUNT_ID = 'de72a2b1-1512-11f1-a3e0-ce6cdc3544e3';

SELECT COUNT(*) FROM DIAMOND_TRANSACTION;