INSERT INTO RECEIVABLE_TXN
    (RECEIVABLE_TXN_ID, TRANSACTION_ID, TRANSACTION_SOURCE, TYPE, DEBTOR_ID, ACCOUNT_ID)
VALUES
    (RECEIVABLE_TXN_ID, TRANSACTION_ID, TRANSACTION_SOURCE, TYPE, DEBTOR_ID, ACCOUNT_ID)
