SELECT
    R.TRANSACTION_SOURCE,
    R.TYPE,
    COALESCE(CASH.DETAILS, CC.DETAILS),
    COALESCE(
            CASE WHEN R.TYPE = 'INCREASE' THEN CASH.AMOUNT ELSE -CASH.AMOUNT END,
            CASE WHEN R.TYPE = 'INCREASE' THEN CC.AMOUNT ELSE -CC.AMOUNT END
    ) AS AMOUNT
     -- SUM( COALESCE(CASH.AMOUNT, CC.AMOUNT))
FROM
    RECEIVABLE_TXN R

LEFT JOIN CASH_TXN CASH ON R.TRANSACTION_ID = CASH.CASH_TXN_ID
LEFT JOIN CREDIT_CARD_TXN CC ON R.TRANSACTION_ID = CC.CREDIT_CARD_TXN_ID

WHERE
    R.ACCOUNT_ID='cd2fe940-0398-11f1-8f82-0242ac160002'

ORDER BY R.CREATED DESC