START TRANSACTION;

SET @CREDIT_CARD_TXN_ID = UUID();
SET @GL_HEADER_ID = UUID();

-- INCREASE
# SET @DEBIT_GL_ACCOUNT_CODE = -5000;
# SET @CREDIT_GL_ACCOUNT_CODE = 2000;
-- DECREASE
SET @DEBIT_GL_ACCOUNT_CODE = 2000;
SET @CREDIT_GL_ACCOUNT_CODE = 1000;

SET @DETAILS = 'Repaid';
SET @AMOUNT = 80.00;
SET @DATE = '2026-02-14';
SET @MERCHANT_ID = NULL;
SET @SOURCE_TYPE = 'CREDIT_CARD';

SET @ACCOUNT_ID = '7e7e02f7-035a-11f1-8f82-0242ac160002';

INSERT INTO CREDIT_CARD_TXN
    (CREDIT_CARD_TXN_ID, ACCOUNT_ID, DETAILS, AMOUNT, DATE, TRANSACTION_SOURCE, MERCHANT_ID)
VALUES
    (@CREDIT_CARD_TXN_ID, @ACCOUNT_ID, @DETAILS, @AMOUNT, @DATE, 'CREDIT_CARD', @MERCHANT_ID);


INSERT INTO GL_HEADER
    (GL_HEADER_ID, TRANSACTION_ID, SOURCE_TYPE, DETAILS, ACCOUNT_ID)
VALUES
    (@GL_HEADER_ID, @CREDIT_CARD_TXN_ID, @SOURCE_TYPE, @DETAILS, @ACCOUNT_ID);


INSERT INTO GL_LINE
    (GL_LINE_ID, GL_ACCOUNT_ID, GL_HEADER_ID, DEBIT_CREDIT, ACCOUNT_ID, AMOUNT)
values
    (UUID(), (SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT_CODE=@DEBIT_GL_ACCOUNT_CODE  AND ACCOUNT_ID=@ACCOUNT_ID), @GL_HEADER_ID, 'DEBIT',  @ACCOUNT_ID, @AMOUNT), -- DEBIT
    (UUID(), (SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT_CODE=@CREDIT_GL_ACCOUNT_CODE AND ACCOUNT_ID=@ACCOUNT_ID), @GL_HEADER_ID, 'CREDIT', @ACCOUNT_ID, @AMOUNT); -- CREDIT

SELECT * FROM CREDIT_CARD_TXN WHERE ACCOUNT_ID=@ACCOUNT_ID;

COMMIT;