SET @TXN_ID='145a2294-4109-4f9d-b47d-88061eaad313';
SELECT
    CC.CREDIT_CARD_TXN_ID AS CC_ID,
    GL_HEADER.DETAILS AS GL_HEADER_DETAILS,
    GL_LINE.GL_ACCOUNT_ID AS GL_LINE_ID,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    CC.RECEIVABLE AS IsRECEIVABLE,
    RECEIVABLE_TXN.RECEIVABLE_TXN_ID
FROM
    CREDIT_CARD_TXN CC

LEFT JOIN RECEIVABLE_TXN ON CC.CREDIT_CARD_TXN_ID = RECEIVABLE_TXN.TRANSACTION_ID
LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    CC.CREDIT_CARD_TXN_ID=@TXN_ID
    OR RECEIVABLE_TXN.TRANSACTION_ID=@TXN_ID
    OR GL_HEADER.TRANSACTION_ID=@TXN_ID
