SELECT
    SUM(CASE WHEN GL_LINE.DEBIT_CREDIT = 'DEBIT' THEN -CC.AMOUNT END) AS DEBIT_BALANCE,
    SUM(CASE WHEN GL_LINE.DEBIT_CREDIT = 'CREDIT' THEN CC.AMOUNT END) AS CREDIT_BALANCE,
    SUM(
            CASE
                WHEN GL_LINE.DEBIT_CREDIT = 'CREDIT' THEN CC.AMOUNT
                WHEN GL_LINE.DEBIT_CREDIT = 'DEBIT' THEN -CC.AMOUNT
                ELSE 0
            END
    )AS OUTSTANDIN_BALANCE
FROM
    CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    GL_ACCOUNT.GL_ACCOUNT_TYPE NOT IN ('ASSET', 'EXPENSE')
    AND GL_HEADER.SOURCE_TYPE = 'CREDIT_CARD'
    AND CC.ACCOUNT_ID='de58d6a9-1512-11f1-a3e0-ce6cdc3544e3';

# SELECT * FROM CREDIT_CARD_TXN WHERE ACCOUNT_ID='32acc5e7-14c7-11f1-a3e0-ce6cdc3544e3';
