SELECT
    CC.DATE,
    CC.DETAILS,
    CC.AMOUNT,
    CC.RECEIVABLE,

    MERCHANT.NAME,
    MERCHANT.TOWN,

    GL_HEADER.SOURCE_TYPE AS 'SOURCE',

    GL_LINE.DEBIT_CREDIT AS 'TXN_TYPE',

    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE

FROM
    CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN MERCHANT ON CC.MERCHANT_ID = MERCHANT.MERCHANT_ID

WHERE
    GL_HEADER.SOURCE_TYPE = 'CREDIT_CARD'