/*
Reason for UNION

This is because of the ACTION column, as one is for INCREASE & the other is for DECREASE, due
to the nature of using DOUBLE_ENTRY accounting.

*/

SELECT
    CC.CREDIT_CARD_TXN_ID,
    CC.DETAILS,
    CC.AMOUNT,
    GL_LINE.DEBIT_CREDIT,

    GL_HEADER.SOURCE_TYPE,

    CASE
        WHEN GL_ACCOUNT_TYPE = 'EXPENSE' AND GL_LINE.DEBIT_CREDIT = 'DEBIT' AND GL_ACCOUNT_CODE BETWEEN 5000 AND 5999 THEN 'INCREASE'
    END AS ACTION,

    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    GL_ACCOUNT.GL_ACCOUNT_TYPE

FROM
    CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    GL_ACCOUNT.GL_ACCOUNT_TYPE NOT IN ('ASSET', 'LIABILITY')
    AND CC.ACCOUNT_ID='cd2fe940-0398-11f1-8f82-0242ac160002'
    AND GL_HEADER.SOURCE_TYPE='CREDIT_CARD'

UNION ALL
# This is for the TXN which decrease the CREDIT_CARD balance
SELECT
    CC.CREDIT_CARD_TXN_ID,
    CC.DETAILS,
    CC.AMOUNT,
    GL_LINE.DEBIT_CREDIT,

    GL_HEADER.SOURCE_TYPE,

    CASE
        WHEN GL_ACCOUNT_TYPE = 'ASSET' AND GL_LINE.DEBIT_CREDIT = 'CREDIT' AND (GL_ACCOUNT_CODE =1000 OR GL_ACCOUNT_CODE BETWEEN 5000 AND 5999) THEN 'DECREASE'
    END AS ACTION,

    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    GL_ACCOUNT.GL_ACCOUNT_TYPE

FROM
    CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    GL_ACCOUNT.GL_ACCOUNT_TYPE NOT IN ('LIABILITY', 'EXPENSE')
    AND CC.ACCOUNT_ID='32acc5e7-14c7-11f1-a3e0-ce6cdc3544e3'
    AND GL_HEADER.SOURCE_TYPE='CREDIT_CARD'
;