CREATE TABLE IF NOT EXISTS CASH_TXN  (
    CASH_TXN_ID UUID PRIMARY KEY NOT NULL,
    ACCOUNT_ID UUID NOT NULL,
    DETAILS TEXT NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    DATE TEXT NOT NULL,
    TRANSACTION_SOURCE TEXT NOT NULL,

    MERCHANT_ID UUID,
    RECEIVABLE BOOLEAN,
    DEBTOR_ID UUID,

    DAY INT,
    DAY_OF_YEAR INT,
    DAY_OF_WEEK TEXT,
    WEEK INT,
    MONTH INT,
    MONTH_NAME TEXT,
    YEAR INT,

    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD_TXN (
    CREDIT_CARD_TXN_ID UUID PRIMARY KEY NOT NULL,
    ACCOUNT_ID UUID NOT NULL,
    DETAILS TEXT NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    DATE TEXT NOT NULL,
    TRANSACTION_SOURCE TEXT NOT NULL,

    MERCHANT_ID UUID,
    RECEIVABLE BOOLEAN,
    DEBTOR_ID UUID,

    DAY INT,
    DAY_OF_YEAR INT,
    DAY_OF_WEEK TEXT,
    WEEK INT,
    MONTH INT,
    MONTH_NAME TEXT,
    YEAR INT,

    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DIAMOND_TRANSACTION(
    TRANSACTION_ID UUID NOT NULL,
    ACCOUNT_ID UUID NOT NULL,

    AMOUNT DOUBLE NOT NULL,
    DETAILS TEXT NOT NULL,

    SOURCE TEXT, # CASH | CREDIT_CARD

    GL_ACCOUNT_ID UUID,
    MERCHANT_ID UUID,

    RECEIVABLE BOOLEAN,
    DEBTOR_ID UUID,

    DATE TEXT NOT NULL,
    DAY INT,
    DAY_OF_YEAR INT,
    DAY_OF_WEEK TEXT,
    WEEK INT,
    MONTH INT,
    YEAR INT,

    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DEBTOR (
    DEBTOR_ID UUID PRIMARY KEY,
    ACCOUNT_ID UUID,
    NAME TEXT,
    DETAILS TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GL_ACCOUNT (
    GL_ACCOUNT_ID UUID PRIMARY KEY,
    GL_ACCOUNT_TYPE TEXT NOT NULL CHECK (
        GL_ACCOUNT_TYPE IN ('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE')
    ),
    GL_ACCOUNT_CODE INT,
    GL_ACCOUNT_NAME TEXT,
    ACCOUNT_ID UUID,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GL_HEADER (
    GL_HEADER_ID UUID PRIMARY KEY,
    SOURCE_TYPE TEXT NOT NULL CHECK (
        SOURCE_TYPE IN ('CASH', 'CREDIT_CARD', 'CREDITOR', 'DEBTOR')
    ),
    TRANSACTION_ID UUID, -- ID OF TXN
    DETAILS TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS GL_LINE (
    GL_LINE_ID UUID PRIMARY KEY,
    GL_ACCOUNT_ID UUID NOT NULL,
    GL_HEADER_ID UUID NOT NULL,
    DEBIT_CREDIT TEXT NOT NULL, -- DEBIT | CREDIT
    AMOUNT DOUBLE NOT NULL,
    ACCOUNT_ID UUID NOT NULL,
    CREATED TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS MERCHANT(
    MERCHANT_ID UUID PRIMARY KEY,
    ACCOUNT_ID UUID NOT NULL,
    NAME TEXT,
    TOWN TEXT,
    LOCATION TEXT,
    SHOPPING_CENTER TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS RECEIVABLE_TXN (
    RECEIVABLE_TXN_ID UUID PRIMARY KEY,
    ACCOUNT_ID UUID,
    TRANSACTION_ID UUID,
    TRANSACTION_SOURCE TEXT,
    TYPE UUID,
    DEBTOR_ID UUID,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID UUID PRIMARY KEY DEFAULT (UUID()),
    USER_ID UUID,
    EMAIL TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DIAMOND_USER(
    ACCOUNT_ID UUID PRIMARY KEY DEFAULT (UUID()),
    DIAMOND_USER_ID UUID,
    EMAIL TEXT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    DATE_OF_BIRTH TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS BUDGET(
    BUDGET_ID UUID PRIMARY KEY,
    ACCOUNT_ID UUID,
    GL_ACCOUNT_ID UUID,
    AMOUNT DOUBLE,
    BUDGET_PERIOD TEXT NOT NULL CHECK(
        BUDGET_PERIOD IN ('WEEK', 'MONTH')
    ),
    CREATED TIMESTAMP DEFAULT NOW()
)