import React from 'react'
import './table.scss'

export default function Page() {
	return (
		<main>
			<div className="outer-wrapper">
				<div className="table-wrapper">
					<table>
						<thead>
							<tr>
								<th>Month</th>
								<th></th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
							</tr>
							<tr className='bottom-header'>
								<th>Col1 is the longest Title</th>
								<th></th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
								<th>h1</th>
							</tr>
						</thead>

						<tbody>
							<tr>
								<td>Col1 ipsum dolor.</td>
								<td>Col1 is the longest Title Lorem,</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
							<tr>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
								<td>DATA</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</main>
	)
}
