START TRANSACTION;

INSERT INTO DIAMOND_TRANSACTION
(
     DIAMOND_TRANSACTION_ID,
     ACCOUNT_ID,
     AMOUNT,
     DETAILS,
     SOURCE,
     TXN_TYPE,
     GL_ACCOUNT_ID,
     MERCHANT_ID,
     RECEIVABLE,
     DEBTOR_ID,
     DATE,
     DAY,
     DAY_OF_YEAR,
     DAY_OF_WEEK,
     WEEK,
     MONTH,
     YEAR,
     CREATED
)

SELECT
    CREDIT_CARD_TXN_ID, -- DIAMOND_TRANSACTION_ID
    CC.ACCOUNT_ID,
    CC.AMOUNT,
    CC.DETAILS,
    'CREDIT_CARD', -- SOURCE
    GL_ACCOUNT.GL_ACCOUNT_TYPE, -- TXN_TYPE
    GL_ACCOUNT.GL_ACCOUNT_ID, -- GL_ACCOUNT_ID
    MERCHANT.MERCHANT_ID,
    RECEIVABLE,
    DEBTOR_ID,
    DATE,
    DAY,
    NULL, -- DAY_OF_YEAR
    DAY_OF_WEEK,
    WEEK,
    MONTH,
    YEAR,
    CC.CREATED

FROM CREDIT_CARD_TXN CC

INNER JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
INNER JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
INNER JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
INNER JOIN MERCHANT ON CC.MERCHANT_ID = MERCHANT.MERCHANT_ID;

COMMIT;