START TRANSACTION;

SET @TXN_ID = 'b0e90b13-37e1-4b8e-a177-e1ca65ff6d68';

DELETE FROM GL_LINE WHERE GL_HEADER_ID=(SELECT GL_HEADER_ID FROM GL_HEADER WHERE TRANSACTION_ID=@TXN_ID);
DELETE FROM GL_HEADER WHERE TRANSACTION_ID=@TXN_ID;
DELETE FROM CASH_TXN WHERE CASH_TXN_ID=@TXN_ID;
DELETE FROM CREDIT_CARD_TXN WHERE CREDIT_CARD_TXN_ID=@TXN_ID;
# DELETE FROM RECEIVABLE_TXN WHERE TRANSACTION_ID=@TXN_ID;

COMMIT;