SELECT
    GL_ACCOUNT.CODE,
    GL_HEADER.SOURCE_TYPE,
    GL_ACCOUNT.NAME,
    GL_LINE.DEBIT_CREDIT,
    CASH_TXN.AMOUNT,
    CASH_TXN.DETAILS

FROM GL_LINE
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN GL_HEADER ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID
LEFT JOIN CASH_TXN ON GL_HEADER.SOURCE_ID = CASH_TXN.CASH_TXN_ID
