SELECT
    GL_ACCOUNT_NAME,
    GL_ACCOUNT_CODE,
    GL_ACCOUNT_TYPE,
    SUM(CC.AMOUNT)

FROM CREDIT_CARD_TXN CC

LEFT JOIN GL_HEADER ON CC.CREDIT_CARD_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    CC.ACCOUNT_ID='de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'

GROUP BY
    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_CODE

ORDER BY GL_ACCOUNT.GL_ACCOUNT_CODE
