SELECT
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    (SELECT ROUND(SUM(IF(TXN_TYPE='INCREASE', AMOUNT, -AMOUNT)), 2) FROM DIAMOND_TRANSACTION WHERE SOURCE='CREDIT_CARD' AND ACCOUNT_ID=@ACCOUNT_ID) AS CREDIT_CARD,
    (SELECT ROUND(SUM(IF(TXN_TYPE='INCOME',   AMOUNT, -AMOUNT)), 2) FROM DIAMOND_TRANSACTION WHERE SOURCE='CASH'        AND ACCOUNT_ID=@ACCOUNT_ID) AS CASH,
    ROUND(SUM(D.AMOUNT), 2) AS TOTAL

FROM DIAMOND_TRANSACTION D

INNER JOIN GL_ACCOUNT ON D.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID  -- 👈 INNER not LEFT

WHERE D.ACCOUNT_ID = @ACCOUNT_ID

GROUP BY
    D.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE

ORDER BY GL_ACCOUNT.GL_ACCOUNT_CODE