# SET @ACCOUNT_ID = 'de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'; # MAIN_ACCOUNT
SET @ACCOUNT_ID = '32acc5e7-14c7-11f1-a3e0-ce6cdc3544e3'; # DEV_ACCOUNT

SELECT
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    SUM(
        IF(TXN_TYPE='INCOME', AMOUNT, -AMOUNT)
    )
FROM
    DIAMOND_TRANSACTION
LEFT JOIN GL_ACCOUNT ON DIAMOND_TRANSACTION.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID  -- 👈 INNER not LEFT

WHERE 
    DIAMOND_TRANSACTION.ACCOUNT_ID=@ACCOUNT_ID
GROUP BY
    DIAMOND_TRANSACTION.GL_ACCOUNT_ID