SELECT
    C.DETAILS,
    C.AMOUNT,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE
FROM
    CASH_TXN C

LEFT JOIN GL_HEADER ON CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    C.ACCOUNT_ID=''
    AND YEAR=2026
    AND MONTH=3