SELECT
    GL_ACCOUNT_NAME,
    GL_ACCOUNT_TYPE,
    SUM(TOTAL)     AS TOTAL,
    SUM(`WEEK-1`)  AS 'WEEK-1',
    SUM(`WEEK-2`)  AS 'WEEK-2',
    SUM(`WEEK-3`)  AS 'WEEK-3',
    SUM(`WEEK-4`)  AS 'WEEK-4',
    SUM(`WEEK-5`)  AS 'WEEK-5',
    SUM(`WEEK-6`)  AS 'WEEK-6',
    SUM(`WEEK-7`)  AS 'WEEK-7',
    SUM(`WEEK-8`)  AS 'WEEK-8',
    SUM(`WEEK-9`)  AS 'WEEK-9',
    SUM(`WEEK-10`) AS 'WEEK-10',
    SUM(`WEEK-11`) AS 'WEEK-11',
    SUM(`WEEK-12`) AS 'WEEK-12'

FROM (

    SELECT
        GL_ACCOUNT_NAME,
        GL_ACCOUNT_TYPE,
        SUM(ROUND(CC.AMOUNT, 2)) AS TOTAL,
        SUM(IF(CC.WEEK = 1,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-1',
        SUM(IF(CC.WEEK = 2,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-2',
        SUM(IF(CC.WEEK = 3,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-3',
        SUM(IF(CC.WEEK = 4,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-4',
        SUM(IF(CC.WEEK = 5,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-5',
        SUM(IF(CC.WEEK = 6,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-6',
        SUM(IF(CC.WEEK = 7,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-7',
        SUM(IF(CC.WEEK = 8,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-8',
        SUM(IF(CC.WEEK = 9,  ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-9',
        SUM(IF(CC.WEEK = 10, ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-10',
        SUM(IF(CC.WEEK = 11, ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-11',
        SUM(IF(CC.WEEK = 12, ROUND(CC.AMOUNT, 2), 0)) AS 'WEEK-12'
    FROM CREDIT_CARD_TXN CC
    LEFT JOIN GL_HEADER  ON CC.CREDIT_CARD_TXN_ID  = GL_HEADER.TRANSACTION_ID
    LEFT JOIN GL_LINE    ON GL_HEADER.GL_HEADER_ID  = GL_LINE.GL_HEADER_ID
    LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID   = GL_ACCOUNT.GL_ACCOUNT_ID
    WHERE CC.ACCOUNT_ID = 'de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'
    GROUP BY GL_ACCOUNT.GL_ACCOUNT_ID, GL_ACCOUNT_NAME, GL_ACCOUNT_CODE, GL_ACCOUNT_TYPE

    UNION ALL

    SELECT
        GL_ACCOUNT_NAME,
        GL_ACCOUNT_TYPE,
        SUM(ROUND(CASH.AMOUNT, 2)) AS TOTAL,
        SUM(IF(CASH.WEEK = 1,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-1',
        SUM(IF(CASH.WEEK = 2,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-2',
        SUM(IF(CASH.WEEK = 3,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-3',
        SUM(IF(CASH.WEEK = 4,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-4',
        SUM(IF(CASH.WEEK = 5,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-5',
        SUM(IF(CASH.WEEK = 6,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-6',
        SUM(IF(CASH.WEEK = 7,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-7',
        SUM(IF(CASH.WEEK = 8,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-8',
        SUM(IF(CASH.WEEK = 9,  ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-9',
        SUM(IF(CASH.WEEK = 10, ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-10',
        SUM(IF(CASH.WEEK = 11, ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-11',
        SUM(IF(CASH.WEEK = 12, ROUND(CASH.AMOUNT, 2), 0)) AS 'WEEK-12'
    FROM CASH_TXN CASH
    LEFT JOIN GL_HEADER  ON CASH.CASH_TXN_ID       = GL_HEADER.TRANSACTION_ID
    LEFT JOIN GL_LINE    ON GL_HEADER.GL_HEADER_ID  = GL_LINE.GL_HEADER_ID
    LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID   = GL_ACCOUNT.GL_ACCOUNT_ID
    WHERE CASH.ACCOUNT_ID = 'de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'
    GROUP BY GL_ACCOUNT.GL_ACCOUNT_ID, GL_ACCOUNT_NAME, GL_ACCOUNT_CODE, GL_ACCOUNT_TYPE

) AS COMBINED

GROUP BY
    GL_ACCOUNT_NAME,
    GL_ACCOUNT_TYPE

ORDER BY
    GL_ACCOUNT_TYPE,
    GL_ACCOUNT_NAME;
