SELECT
    GL_ACCOUNT_NAME,
    SUM(TOTAL) AS TOTAL,
    SUM(`JAN`)  AS 'JAN',
    SUM(`FEB`)  AS 'FEB',
    SUM(`MAR`)  AS 'MAR',
    SUM(`APR`)  AS 'APR',
    SUM(`MAY`)  AS 'MAY',
    SUM(`JUN`)  AS 'JUN',
    SUM(`JUL`)  AS 'JUL',
    SUM(`AUG`)  AS 'AUG',
    SUM(`SEPT`) AS 'SEPT',
    SUM(`OCT`)  AS 'OCT',
    SUM(`NOV`)  AS 'NOV',
    SUM(`DEC`)  AS 'DEC'

FROM (

    SELECT
        GL_ACCOUNT_NAME,
        SUM(ROUND(CC.AMOUNT, 2)) AS TOTAL,
        SUM(IF(CC.MONTH = 1,  ROUND(CC.AMOUNT, 2), 0)) AS 'JAN',
        SUM(IF(CC.MONTH = 2,  ROUND(CC.AMOUNT, 2), 0)) AS 'FEB',
        SUM(IF(CC.MONTH = 3,  ROUND(CC.AMOUNT, 2), 0)) AS 'MAR',
        SUM(IF(CC.MONTH = 4,  ROUND(CC.AMOUNT, 2), 0)) AS 'APR',
        SUM(IF(CC.MONTH = 5,  ROUND(CC.AMOUNT, 2), 0)) AS 'MAY',
        SUM(IF(CC.MONTH = 6,  ROUND(CC.AMOUNT, 2), 0)) AS 'JUN',
        SUM(IF(CC.MONTH = 7,  ROUND(CC.AMOUNT, 2), 0)) AS 'JUL',
        SUM(IF(CC.MONTH = 8,  ROUND(CC.AMOUNT, 2), 0)) AS 'AUG',
        SUM(IF(CC.MONTH = 9,  ROUND(CC.AMOUNT, 2), 0)) AS 'SEPT',
        SUM(IF(CC.MONTH = 10, ROUND(CC.AMOUNT, 2), 0)) AS 'OCT',
        SUM(IF(CC.MONTH = 11, ROUND(CC.AMOUNT, 2), 0)) AS 'NOV',
        SUM(IF(CC.MONTH = 12, ROUND(CC.AMOUNT, 2), 0)) AS 'DEC'

    FROM
        CREDIT_CARD_TXN CC

    LEFT JOIN GL_HEADER  ON CC.CREDIT_CARD_TXN_ID  = GL_HEADER.TRANSACTION_ID
    LEFT JOIN GL_LINE    ON GL_HEADER.GL_HEADER_ID  = GL_LINE.GL_HEADER_ID
    LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID   = GL_ACCOUNT.GL_ACCOUNT_ID

    WHERE
        CC.ACCOUNT_ID = 'de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'
        AND CC.YEAR=2026

    GROUP BY
        GL_ACCOUNT.GL_ACCOUNT_ID,
        GL_ACCOUNT_NAME,
        GL_ACCOUNT_CODE,
        GL_ACCOUNT_TYPE

    UNION ALL

    SELECT
        GL_ACCOUNT_NAME,
        SUM(ROUND(CASH.AMOUNT, 2)) AS TOTAL,
        SUM(IF(CASH.MONTH = 1,  ROUND(CASH.AMOUNT, 2), 0)) AS 'JAN',
        SUM(IF(CASH.MONTH = 2,  ROUND(CASH.AMOUNT, 2), 0)) AS 'FEB',
        SUM(IF(CASH.MONTH = 3,  ROUND(CASH.AMOUNT, 2), 0)) AS 'MAR',
        SUM(IF(CASH.MONTH = 4,  ROUND(CASH.AMOUNT, 2), 0)) AS 'APR',
        SUM(IF(CASH.MONTH = 5,  ROUND(CASH.AMOUNT, 2), 0)) AS 'MAY',
        SUM(IF(CASH.MONTH = 6,  ROUND(CASH.AMOUNT, 2), 0)) AS 'JUN',
        SUM(IF(CASH.MONTH = 7,  ROUND(CASH.AMOUNT, 2), 0)) AS 'JUL',
        SUM(IF(CASH.MONTH = 8,  ROUND(CASH.AMOUNT, 2), 0)) AS 'AUG',
        SUM(IF(CASH.MONTH = 9,  ROUND(CASH.AMOUNT, 2), 0)) AS 'SEPT',
        SUM(IF(CASH.MONTH = 10, ROUND(CASH.AMOUNT, 2), 0)) AS 'OCT',
        SUM(IF(CASH.MONTH = 11, ROUND(CASH.AMOUNT, 2), 0)) AS 'NOV',
        SUM(IF(CASH.MONTH = 12, ROUND(CASH.AMOUNT, 2), 0)) AS 'DEC'

    FROM
        CASH_TXN CASH

    LEFT JOIN GL_HEADER  ON CASH.CASH_TXN_ID        = GL_HEADER.TRANSACTION_ID
    LEFT JOIN GL_LINE    ON GL_HEADER.GL_HEADER_ID   = GL_LINE.GL_HEADER_ID
    LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID    = GL_ACCOUNT.GL_ACCOUNT_ID

    WHERE
        CASH.ACCOUNT_ID = 'de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'
        AND CASH.YEAR=2026

    GROUP BY
        GL_ACCOUNT.GL_ACCOUNT_ID,
        GL_ACCOUNT_NAME,
        GL_ACCOUNT_CODE,
        GL_ACCOUNT_TYPE

) AS COMBINED

GROUP BY GL_ACCOUNT_NAME
ORDER BY GL_ACCOUNT_NAME