spring.application.name=Diamond_Core

# MariaDB Connection
spring.datasource.url=jdbc:mariadb://localhost:3317/DIAMOND_PERSONAL
spring.datasource.username=dev
spring.datasource.password=diamond
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
