START TRANSACTION;

SET @ACCOUNT_ID='96e017ac-16b7-464d-93c2-653d396b609b';

SET @ASSET_NAME = 'Bank';
SET @LIABILITY_NAME = 'Credit Card';
SET @EQUITY_NAME = 'Capital Contribution';
SET @INCOME_NAME = 'Semper-Salary';
SET @EXPENSE_NAME = 'Sweets';

INSERT INTO GL_ACCOUNT
    (GL_ACCOUNT_ID, GL_ACCOUNT_TYPE, GL_ACCOUNT_CODE, GL_ACCOUNT_NAME, ACCOUNT_ID)
VALUES
    (UUID(),'ASSET', '1000', @ASSET_NAME, @ACCOUNT_ID),
    (UUID(),'LIABILITY', '2000', @LIABILITY_NAME, @ACCOUNT_ID),
    (UUID(),'EQUITY', '3000', @EQUITY_NAME, @ACCOUNT_ID),
    (UUID(),'INCOME', '2000', @INCOME_NAME, @ACCOUNT_ID),
    (UUID(),'EXPENSE', '5000', @EXPENSE_NAME, @ACCOUNT_ID);

COMMIT;