#SET @ACCOUNT_ID='';

SELECT
    GL_ACCOUNT.GL_ACCOUNT_NAME AS NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE AS TYPE,
    BUDGET.AMOUNT,
    SUM(CASH.AMOUNT) AS AMOUNT,
    GL_HEADER.SOURCE_TYPE,
    CASH.WEEK
FROM BUDGET
LEFT JOIN GL_ACCOUNT ON BUDGET.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN GL_LINE ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN GL_HEADER ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID
LEFT JOIN CASH_TXN CASH ON CASH.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID


WHERE
    BUDGET.ACCOUNT_ID='de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'
    AND GL_ACCOUNT.GL_ACCOUNT_TYPE <> 'ASSET'
    AND GL_HEADER.SOURCE_TYPE='CASH'

GROUP BY
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    BUDGET.AMOUNT,
    CASH.DETAILS,
    GL_HEADER.SOURCE_TYPE

