SELECT
    D.DATE,
    D.MONTH,
    D.DETAILS,
    D.AMOUNT,
    D.SOURCE,
    D.TXN_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_ID,
    GL_ACCOUNT.GL_ACCOUNT_TYPE,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_ACCOUNT.GL_ACCOUNT_CODE,
    D.MERCHANT_ID,
    MERCHANT.NAME

FROM
    DIAMOND_TRANSACTION D
LEFT JOIN GL_ACCOUNT ON D.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN MERCHANT ON D.MERCHANT_ID = MERCHANT.MERCHANT_ID

WHERE
    D.ACCOUNT_ID='32acc5e7-14c7-11f1-a3e0-ce6cdc3544e3';


