CREATE TABLE IF NOT EXISTS DIAMOND_TRANSACTION(
    DIAMOND_TRANSACTION_ID UUID,
    ACCOUNT_ID UUID,

    AMOUNT DOUBLE,
    DETAILS TEXT,

    TXN_TYPE TEXT, # INCOME | EXPENSE | INCREASE | DECREASE
    SOURCE TEXT, # CASH | CREDIT_CARD

    GL_ACCOUNT_ID UUID,
    MERCHANT_ID UUID,

    RECEIVABLE BOOLEAN,
    DEBTOR_ID UUID,

    DATE TEXT NOT NULL,
    DAY INT,
    DAY_OF_YEAR INT,
    DAY_OF_WEEK TEXT,
    WEEK INT,
    MONTH INT,
    YEAR INT,

    CREATED TIMESTAMP DEFAULT NOW()
);