SELECT
    CASH_TXN.DETAILS,
    CASH_TXN.AMOUNT,
    CASH_TXN.DATE,
    CASH_TXN.CASH_TXN_ID,
    GL_ACCOUNT.GL_ACCOUNT_NAME,
    GL_LINE.DEBIT_CREDIT,
    CASH_TXN.DAY,
    CASH_TXN.DAY_OF_WEEK,
    CASH_TXN.WEEK,
    CASH_TXN.MONTH,
    CASH_TXN.MONTH_NAME,
    CASH_TXN.YEAR
FROM CASH_TXN
LEFT JOIN GL_HEADER ON CASH_TXN.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
WHERE
    CASH_TXN.ACCOUNT_ID='6857ad8a-02ca-11f1-8f82-0242ac160002'