SELECT
    SUM(CASE WHEN GL_ACCOUNT_TYPE='INCOME' THEN CASH_TXN.AMOUNT END) AS INCOME,
    SUM (CASE WHEN GL_ACCOUNT_TYPE='EXPENSE' THEN -CASH_TXN.AMOUNT END) AS EXPENSE,

    SUM(
        CASE
            WHEN GL_ACCOUNT_TYPE='EXPENSE' THEN -CASH_TXN.AMOUNT ELSE CASH_TXN.AMOUNT
        END
    ) AS BALANCE

FROM
    CASH_TXN

LEFT JOIN GL_HEADER ON CASH_TXN.CASH_TXN_ID = GL_HEADER.TRANSACTION_ID
LEFT JOIN GL_LINE ON GL_HEADER.GL_HEADER_ID = GL_LINE.GL_HEADER_ID
LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID

WHERE
    CASH_TXN.ACCOUNT_ID='dfdec9eb-0308-11f1-8f82-0242ac160002'
     AND GL_ACCOUNT.GL_ACCOUNT_TYPE IN ('EXPENSE', 'INCOME')