CREATE TABLE CASH_TXN (
    CASH_TXN_ID UUID PRIMARY KEY NOT NULL,
    ACCOUNT_ID UUID NOT NULL,
    DETAILS TEXT NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    DATE TEXT NOT NULL,
    TRANSACTION_SOURCE TEXT NOT NULL,

    MERCHANT_ID UUID,

    DAY INT,
    DAY_OF_WEEK TEXT,
    WEEK INT,
    MONTH INT,
    MONTH_NAME TEXT,
    YEAR INT,

    CREATED TIMESTAMP DEFAULT NOW()
)