CREATE TABLE GL_ACCOUNT (
    GL_ACCOUNT_ID UUID PRIMARY KEY,
    GL_ACCOUNT_TYPE TEXT NOT NULL CHECK (
        GL_ACCOUNT_TYPE IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE')
    ),
    GL_ACCOUNT_CODE INT,
    GL_ACCOUNT_NAME TEXT,
    accountID UUID,
    CATEGORY_ID UUID,
    CREATED TIMESTAMP DEFAULT NOW()
)