CREATE TABLE GL_HEADER (
    GL_HEADER_ID UUID PRIMARY KEY,
    SOURCE_TYPE TEXT NOT NULL CHECK (
        SOURCE_TYPE IN ('CASH', 'CREDIT_CARD', 'CREDITOR', 'DEBTOR')
    ),
    SOURCE_ID UUID, -- ID OF TXN
    DETAILS TEXT,
    CREATED TIMESTAMP DEFAULT NOW()
)