CREATE TABLE GL_LINE (
    GL_LINE_ID UUID PRIMARY KEY,
    GL_ACCOUNT_ID UUID NOT NULL,
    GL_HEADER_ID UUID NOT NULL,
    DEBIT_CREDIT TEXT NOT NULL, -- DEBIT | CREDIT
    AMOUNT DOUBLE NOT NULL, -- Details per line
    USER_ACCOUNT_ID UUID NOT NULL,
    CREATED TIMESTAMP DEFAULT NOW() NOT NULL
)