CREATE TABLE IF NOT EXISTS RECEIVABLE_TXN (
    RECEIVABLE_TXN_ID UUID PRIMARY KEY,
    ACCOUNT_ID UUID,
    TRANSACTION_ID UUID,
    TRANSACTION_SOURCE TEXT,
    TYPE UUID,
    DEBTOR_ID UUID,
    CREATED TIMESTAMP DEFAULT NOW()
);