SET @MERCHANT_ID = UUID();
SET @NAME = 'Checkers Liquor - Paardevelei';
SET @TOWN = 'Somerset West';
SET @SHOPPING_CENTER='Paardevelie';
SET @ACCOUNT_ID='de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'; #MAIN
# SET @ACCOUNT_ID = '32acc5e7-14c7-11f1-a3e0-ce6cdc3544e3'; #DEV
INSERT INTO MERCHANT
    (MERCHANT_ID, NAME, TOWN, SHOPPING_CENTER, ACCOUNT_ID)
VALUES
    (UUID(), @NAME, @TOWN, @SHOPPING_CENTER, @ACCOUNT_ID)
RETURNING MERCHANT_ID, NAME, ACCOUNT_ID