SELECT
    GL_ACCOUNT_TYPE,
    D.ACCOUNT_ID,
     SUM(
             CASE
                WHEN D.TXN_TYPE='EXPENSE' AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='EXPENSE'  AND MONTH='3}' THEN D.AMOUNT
                WHEN D.TXN_TYPE='INCOME'  AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='EXPENSE' AND MONTH='3' THEN -D.AMOUNT

                WHEN D.TXN_TYPE='INCOME'  AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='INCOME' AND MONTH='3' THEN D.AMOUNT

                WHEN D.TXN_TYPE='INCREASE' AND SOURCE='CREDIT_CARD' AND GL_ACCOUNT_TYPE='EXPENSE' AND MONTH='3' THEN D.AMOUNT
                ELSE 0
            END
     ) AS ACTUAL_MAR,
     SUM(
        CASE
            WHEN D.TXN_TYPE='EXPENSE' AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='EXPENSE'  AND MONTH='4' THEN D.AMOUNT
            WHEN D.TXN_TYPE='INCOME'  AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='EXPENSE' AND MONTH='4' THEN -D.AMOUNT

            WHEN D.TXN_TYPE='INCOME'  AND SOURCE='CASH' AND GL_ACCOUNT_TYPE='INCOME' AND MONTH='4' THEN D.AMOUNT

            WHEN D.TXN_TYPE='INCREASE' AND SOURCE='CREDIT_CARD' AND GL_ACCOUNT_TYPE='EXPENSE' AND MONTH='4' THEN D.AMOUNT
            ELSE 0
        END
     ) AS ACTUAL_APR
FROM
    DIAMOND_TRANSACTION D

LEFT JOIN GL_ACCOUNT ON D.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID
LEFT JOIN BUDGET ON D.GL_ACCOUNT_ID = BUDGET.GL_ACCOUNT_ID WHERE BUDGET.GL_ACCOUNT_ID IS NULL AND D.ACCOUNT_ID='de58d6a9-1512-11f1-a3e0-ce6cdc3544e3'

GROUP BY GL_ACCOUNT_TYPE