START TRANSACTION;

# UPDATE CASH_TXN ======================================================================================================================================
UPDATE CASH_TXN
    SET
        AMOUNT=@TXN_AMOUNT,
        DETAILS=@TXN_DETAILS,
        MERCHANT_ID=@TXN_MERCHANT_ID,
        RECEIVABLE=@RECEIVABLE,
        DATE=@TXN_DATE,
        DAY=@TXN_DAY,
        DAY_OF_WEEK=@TXN_DAY_OF_WEEK,
        WEEK=@TXN_WEEK,
        MONTH=@TXN_MONTH,
        MONTH_NAME=@TXN_MONTH_NAME,
        YEAR=@TXN_YEAR

    WHERE
        ACCOUNT_ID=@TXN_ACCOUNT_ID
        AND CASH_TXN_ID=@TXN_ID;

# UPDATING THE NOMINAL GL_LINE (EXPENSE | INCOME) ========================================================================================================
UPDATE
    GL_LINE

SET
    DEBIT_CREDIT=@TXN_NOMINAL_DEBIT_CREDIT,
    AMOUNT=@TXN_AMOUNT,
    GL_ACCOUNT_ID=(SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT.GL_ACCOUNT_CODE=@TXN_GL_ACCOUNT_CODE_DEBIT AND GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID)

WHERE
    GL_LINE.GL_HEADER_ID=@TXN_GL_HEADER_ID
    #   WORKING
    AND GL_ACCOUNT_ID=(SELECT GL_ACCOUNT.GL_ACCOUNT_ID FROM GL_LINE LEFT JOIN GL_ACCOUNT ON GL_LINE.GL_ACCOUNT_ID = GL_ACCOUNT.GL_ACCOUNT_ID WHERE GL_HEADER_ID=@TXN_GL_HEADER_ID AND  GL_ACCOUNT_TYPE IN ('INCOME', 'EXPENSE') AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID) # FIND THE LINE WHICH IS AN INCOME OR EXPENSE
    AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID;

# UPDATING THE BALANCE SHEET GL LINE (ASSET|LIABILITY) ========================================================================================================
UPDATE
    GL_LINE

SET
    DEBIT_CREDIT=@TXN_BALANCE_SHEET_DEBIT_CREDIT,
    AMOUNT=@TXN_AMOUNT,
    GL_ACCOUNT_ID=(SELECT GL_ACCOUNT_ID FROM GL_ACCOUNT WHERE GL_ACCOUNT.GL_ACCOUNT_CODE=1000 AND GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID) # SETTING THE DIAMOND_USER'S BANK ACCOUNT

WHERE
    GL_LINE.GL_HEADER_ID=@TXN_GL_HEADER_ID

    AND GL_ACCOUNT_ID=(
        SELECT
            GL_ACCOUNT.GL_ACCOUNT_ID
        FROM
            GL_ACCOUNT

        LEFT JOIN GL_LINE ON GL_ACCOUNT.GL_ACCOUNT_ID = GL_LINE.GL_ACCOUNT_ID
        LEFT JOIN GL_HEADER ON GL_LINE.GL_HEADER_ID = GL_HEADER.GL_HEADER_ID

        WHERE
            GL_HEADER.GL_HEADER_ID=@TXN_GL_HEADER_ID AND
            GL_ACCOUNT.GL_ACCOUNT_TYPE IN ('ASSET') AND
            GL_ACCOUNT.ACCOUNT_ID=@TXN_ACCOUNT_ID
    )

    AND GL_LINE.ACCOUNT_ID=@TXN_ACCOUNT_ID;


COMMIT;




