import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./Components/Header/Header.jsx";
import Nav from "./Components/Nav/Nav";
import NavAuth from "./(components)/NavAuth";
import AuthProvider from "./(components)/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Diamond",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

			{/* The auth provider is for client side Auth */}
			<AuthProvider>
				<Header />
				<Nav />
			
				{children}
			</AuthProvider>
		</body>
		</html>
  );
}
