import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./Components/Header/Header.jsx";
import Nav from "./Components/Nav/Nav";
import AuthProvider from "./(components)/AuthProvider";
// import Footer from "./Components/Footer/Footer";

import './layout.scss'
import SideBar from "./Sidebar/SideBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Diamond",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

			{/* The auth provider is for client side Auth */}
			<AuthProvider>
				<div className="layout">

					<aside className="sidebar">
						<SideBar/>
					</aside>

					<main className="content">
						{children}	

					</main>
				</div>
			
			</AuthProvider>
		</body>
		</html>
  );
}
